## Basic Configuration
baseurl = "https://hellohy.github.io"
languageCode = "zh-CN"

theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = ""
# googleAnalytics = ""
# enableRobotsTXT = true

## Site Settings
[params]
    author = "Hellohy"
    title = "Title"
    # description = "..."
    authorimage = "/img/about.jpg"
    dateformat = "2006-01-02 15:04"
    highlightjs = true
    # highlightjsstyle = "github"

## Social Accounts
[params.social]
    github = "hellohy"
    # instagram = "<username>"
    # xing = "<username>"
    # linkedin = "<username>"
    # twitter = "<username>"
    # facebook = "<username>"
    # stackoverflow = "<username>"
    email = "hitcloudy@gmail.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"
